### ISSUE TITLE
2018/04/26

### ISSUE THREAD

**Issue by mowatermelon** [mowatermelon/studyNode#133]
```javascript
/**
 * 定义应用路由
 */
import React from 'react';
import {
  Router,
  // browserHistory,
  hashHistory,
} from 'react-router';

// 路由配置规则参考： https://github.com/ReactTraining/react-router/blob/v3/docs/guides/RouteConfiguration.md#configuration-with-plain-routes
// 一下部分是由 ICE 相关工具自动生成的路由，请勿随意改变，否则可能会出现一些异常情况
// <!-- auto generated routes start -->
import Home from './pages/Home';
import BlankLayout from './layouts/BlankLayout';
import NotFound from './pages/NotFound';

const autoGeneratedRoutes = [
  {
    path: '/',
    childRoutes: [{ path: '*', childRoutes: [], component: NotFound }],
    component: BlankLayout,
    indexRoute: { component: Home },
  },
];

// <!-- auto generated routes end -->

// 自定义路由，如果 path 相同则会覆盖自动生成部分的路由配置
const customRoutes = [];

export default (
  <Router
    history={hashHistory}
    routes={[...autoGeneratedRoutes, ...customRoutes]}
  />
);

```

**Comment by mowatermelon** [comment]
```css

.table-container {
  display: table;
  .cell {
    display: table-cell;
    vertical-align: middle;
  }
}

.help-center{
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  margin: auto;
  height: 340px;
  width: 795px;

}
```
