### ISSUE TITLE
2018/5/11

### ISSUE THREAD

**Issue by mowatermelon** [mowatermelon/studyNode#142]
```css
xmp, pre, plaintext {
  display: block;
  font-family: -moz-fixed;
  white-space: pre;
  margin: 1em 0;
}

```

值 | 描述
-- | --
normal | 默认。空白会被浏览器忽略。
pre | 空白会被浏览器保留。其行为方式类似 HTML 中的 <pre> 标签。
nowrap | 文本不会换行，文本会在在同一行上继续，直到遇到 <br> 标签为止。
pre-wrap | 保留空白符序列，但是正常地进行换行。
pre-line | 合并空白符序列，但是保留换行符。
inherit | 规定应该从父元素继承 white-space 属性的值。

有个pre-wrap，保留空白符序列，但是正常地进行换行。

```css
pre {
  white-space: pre-wrap;
  white-space: pre-wrap;
  word-wrap: break-word;
}

```
