### ISSUE TITLE
2018/05/24

### ISSUE THREAD

**Issue by mowatermelon** [mowatermelon/studyNode#151]
```css
.sidebar #accordion{
    -webkit-animation-name: move_left;
    animation-name: move_left;
    -webkit-animation-duration: 1s;
    animation-duration: 1s;
    -webkit-animation-iteration-count: 1;
    animation-iteration-count: 1;
    -webkit-animation-fill-mode: forwards;
    animation-fill-mode: forwards;
    color:rgba(21, 87, 148, 0.3);
    width: 60px;
}

.sidebar #accordion.open{
    /* -webkit-transform: translateX(0);
    transform: translateX(0); */
    width: 220px;
    color:#fff;
    -webkit-animation-name: move_right;
    animation-name: move_right;
    -webkit-animation-duration: 1s;
    animation-duration: 1s;
    -webkit-animation-iteration-count: 1;
    animation-iteration-count: 1;
    -webkit-animation-fill-mode: forwards;
    animation-fill-mode: forwards;
}
@keyframes move_left {
    from {
        opacity: 0;
        width: 220px;
      }
      to {
        opacity: 1;
        -webkit-transform: translateX(-10px);
        transform: translateX(-10px);
      }
  }
@keyframes move_right {
    from {
        opacity: 0;
        color:rgba(21, 87, 148, 0.3);
      }
      to {
        opacity: 1;
        -webkit-transform: translateX(0%);
        transform: translateX(0%);
      }
  }

```
