### ISSUE TITLE
2018/05/29

### ISSUE THREAD

**Issue by mowatermelon** [mowatermelon/studyNode#154]
```javascript

				const tempRandom = Math.floor(Math.random()*5 + 1);
				const bgDom = document.getElementsByClassName('themeBackground')[0];
				const oldTheme = bgDom.classList[3];
				bgDom.classList.replace(oldTheme,'theme0'+tempRandom);
				bgDom.classList.remove(oldTheme).add('theme0'+tempRandom);
```

**Comment by mowatermelon** [comment]
```css
@media print {
  .d-print-none {
    display: none !important
  }
  .d-print-inline {
    display: inline !important
  }
  .d-print-inline-block {
    display: inline-block !important
  }
  .d-print-block {
    display: block !important
  }
  .d-print-table {
    display: table !important
  }
  .d-print-table-row {
    display: table-row !important
  }
  .d-print-table-cell {
    display: table-cell !important
  }
  .d-print-flex {
    display: -webkit-box !important;
    display: -ms-flexbox !important;
    display: flex !important
  }
  .d-print-inline-flex {
    display: -webkit-inline-box !important;
    display: -ms-inline-flexbox !important;
    display: inline-flex !important
  }
}


```
