### ISSUE TITLE
2018/06/08

### ISSUE THREAD

**Issue by mowatermelon** [mowatermelon/studyNode#162]
设置select的选中之后的效果

```css
.custom-select:focus::-ms-value {
  color: #495057;
  background-color: #fff
}
```
