### ISSUE TITLE
伪类大作战

### ISSUE THREAD

**Issue by mowatermelon** [mowatermelon/studyNode#179]
The :optional CSS pseudo-class represents any <input>, <select>, or <textarea> element that does not have the required attribute set on it.

```css
/* Selects any optional <input> */
input:optional {
  border: 1px dashed black;
}

```

This pseudo-class is useful for styling fields that are not required to submit a form.
