### ISSUE TITLE
伪类大作战

### ISSUE THREAD

**Issue by mowatermelon** [mowatermelon/studyNode#180]
The `:optional` CSS pseudo-class represents any `<input>`, `<select>`, or `<textarea>` element that does not have the required attribute set on it.

```css
/* Selects any optional <input> */
input:optional {
  border: 1px dashed black;
}

```

This pseudo-class is useful for styling fields that are not required to submit a form.

**Comment by mowatermelon** [comment]
# :required

The :required CSS pseudo-class represents any `<input>`, `<select>`, or `<textarea>` element that has the required attribute set on it.

```css
/* Selects any required <input> */
input:required {
  border: 1px dashed red;
}
```

This pseudo-class is useful for highlighting fields that must have valid data before a form can be submitted.

Note: The` :optional` pseudo-class selects optional form fields.

**Comment by mowatermelon** [comment]
# :required

The :invalid CSS pseudo-class represents any <input> or other <form> element whose contents fail to validate.

```css
/* Selects any invalid <input> */
input:invalid {
  background-color: pink;
}
```

This pseudo-class is useful for highlighting field errors for the user.

**Comment by mowatermelon** [comment]
```css
select:not(:-internal-list-box) {
    overflow: visible !important;
}
```
