### ISSUE TITLE
3D bridge

### ISSUE THREAD

**Issue by mowatermelon** [mowatermelon/studyNode#208]
![image](https://user-images.githubusercontent.com/18508817/50049886-9a912080-0129-11e9-921e-5fbec5d7120c.png)

![image](https://user-images.githubusercontent.com/18508817/50049888-b09ee100-0129-11e9-9726-bc5ae7c7a82e.png)

### selector ~ selector

```css
.c_mesh_fill:checked ~ .container > .ground{}
```

### selector + selector

```css
.scale:hover + .container {}
```

### selector > selector

```css
.container > .ground {}
```

### variable

```css
:root {
    --z_interface: 999;
    --boat_z:3; 
    --ground_size: 120em;
    --ground_color: #006400;
    --ground_anim_state:paused;
    --river_color:linear-gradient(to right, #234567, #012345 25%, #012345 75%,#234567);
    --barrier_color:#671610;
}
.barrier.shadow {
    height:calc(var(--barrier_height)/2);
    --barrier_color:#333;
}
.barrier {
    position:absolute;
    transform-style:preserve-3d;
    height:var(--barrier_height);
    width:100%;
    border-top:calc(2*var(--skeleton_width)) var(--barrier_color) solid;
    border-bottom:calc(2*var(--skeleton_width)) var(--barrier_color) solid;
    background:repeating-linear-gradient(45deg, transparent, transparent 5px,
        var(--barrier_color) 5px, var(--barrier_color) 7px, transparent 7px),
    repeating-linear-gradient(-45deg, transparent, transparent 5px,
        var(--barrier_color) 5px, var(--barrier_color) 7px, transparent 7px);
}
```

### calculate

```css
 .road {
    position:absolute;
    width:100%;
    height:calc(var(--pos_s2) - var(--pos_s1));
    background:var(--road_color);
    top:calc(50% - (var(--pos_s2) - var(--pos_s1))/2);
    transform:translateZ(calc(var(--pillars_height)/7));
    border:var(--skeleton_width) var(--skeleton_color) solid;
    transform-style:preserve-3d;
}
.pillar11 { left:25%; top:calc(-1*var(--pillars_height)/2 + var(--pos_s1) - var(--pillars_width)/2); }
```

### animation-play-state

```css
animation-play-state:paused;
animation-play-state:paused, running;
animation-play-state:running,running;
```

### translate

```css
transform:translateZ(1px);

transform:rotateX(90deg) translateZ(var(--underground_hheight)) translateY(calc(-1*var(--underground_hheight)));

transform:rotateX(90deg) translateZ(calc(-60em + var(--underground_hheight))) translateY(calc(-1*var(--underground_hheight)));
```

### transform-origin

```css
transform-origin:center center 0;

transform-origin:50% 50% 0;

transform-origin:0% 100%;

transform-origin:0% 0% 0px;
```

### transform-style

```css
transform-style:preserve-3d;
```

### perspective

```css
perspective:1000px;
```

### repeating-linear-gradient

```css
background:repeating-linear-gradient(45deg, transparent, transparent 6px,var(--skeleton_color) 6px, var(--skeleton_color) 8px, transparent 8px),repeating-linear-gradient(-45deg, transparent, transparent 6px,var(--skeleton_color) 6px,var(--skeleton_color) 8px, transparent 8px);
```

### animation-delay

```css
.wave_left_2 { animation:wave_left 15s ease-out infinite; left:5%;
    animation-delay:-5s; }
.wave_left_3 { animation:wave_left 15s ease-out infinite; left:5%;
    animation-delay:-10s; }
.wave_right_1 { animation:wave_right 15s ease-out infinite; right:5%; }
.wave_right_2 { animation:wave_right 15s ease-out infinite; right:5%;
    animation-delay:-5s; }
.wave_right_3 { animation:wave_right 15s ease-out infinite; right:5%;
    animation-delay:-10s; }
```

### svg attribute

```css
fill:transparent;
stroke:white;
```

**Comment by mowatermelon** [comment]
## 前置知识

### selector ~ selector

```css
/* Select each .container element preceded by .c_mesh_fill:checked*/
/* 选择前面有 .c_mesh_fill类并且为选中状态 的元素的每个 .container 元素。*/
.c_mesh_fill:checked ~ .container{}
```

---

### selector + selector

```css
/* Select all .container elements immediately after the .scale:hover element.*/
/* 选择紧接在 .scale:hover 元素之后的所有 .container 元素。*/
.scale:hover + .container {}
```

---

### selector > selector

```css
/* Select all .ground elements whose parent element is .container*/
/* 选择父元素为 .container 元素的所有 .ground 元素。*/
.container > .ground {}
```

---

**Comment by mowatermelon** [comment]
## 前置知识


### css 变量

- https://developer.mozilla.org/zh-CN/docs/Web/CSS/:root

- https://developer.mozilla.org/zh-CN/docs/Web/CSS/Value_definition_syntax

- https://developer.mozilla.org/zh-CN/docs/Web/CSS/Using_CSS_variables

- https://developer.mozilla.org/zh-CN/docs/Web/API/Window/getComputedStyle

> 基础规范

变量值可以是各种，可以是`数字(3)`，`数字加单位值(120em)`，`颜色值(#006400)`，和`渐变值(linear-gradient(to right, #234567, #012345 25%, #012345 75%,#234567))`等等，只要是在css中可以单项出现的值，都可以用于`CSS变量赋值`。

如果是在`:root`节点下声明的`CSS变量`，则为全局的`CSS变量`，如果在具体选择器内部写的`CSS变量`，则通过层级关系，元素下面的子元素可以继承和使用该`CSS变量`。

| 声明规范                     | 基础案例         |
|--------------------------|--------------|
| `--{varName}:{varValue}` | `--boat_z:3` |

`CSS变量`使用的完整语法为：`var( [, ]? )`，用中文表示就是：`var( <自定义属性名> [, <默认值 ]? )`，也即是如果我们没有定义变量值，那么就会使用后面的值作为其默认属性值。

变量值可以单一使用，也可以混合其他样式值，在一起使用。

| 使用规范               | 基础案例                                                                                                                                                                                                                                                                                             |
|--------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `var(--{varName})` | `var(--barrier_height)`,`repeating-linear-gradient(45deg, transparent, transparent 5px,var(--barrier_color) 5px, var(--barrier_color) 7px, transparent 7px),repeating-linear-gradient(-45deg, transparent, transparent 5px,var(--barrier_color) 5px, var(--barrier_color) 7px, transparent 7px)` |

```css
:root {
    --z_interface: 999;
    --boat_z: 3;
    --ground_size: 120em;
    --ground_color: #006400;
    --ground_anim_state: paused;
    --river_color: linear-gradient(to right, #234567, #012345 25%, #012345 75%, #234567);
    --barrier_color: #671610;
}

.barrier.shadow {
    height: calc(var(--barrier_height)/2);
    --barrier_color: #333;
}

.barrier {
    position: absolute;
    transform-style: preserve-3d;
    height: var(--barrier_height);
    width: 100%;
    border-top: calc(2*var(--skeleton_width)) var(--barrier_color, red) solid;
    border-bottom: calc(2*var(--skeleton_width)) var(--barrier_color) solid;
    background: repeating-linear-gradient(45deg, transparent, transparent 5px,
        var(--barrier_color) 5px, var(--barrier_color) 7px, transparent 7px),
        repeating-linear-gradient(-45deg, transparent, transparent 5px,
        var(--barrier_color) 5px, var(--barrier_color) 7px, transparent 7px);
}
```

  ---

> 结合js

- 样式文件中的`CSS变量`获取

```html
<p class="testCssVar">西瓜测试样式文件中CSS变量获取</p>
```

```css
.testCssVar{
    --test_color:#c42727;
    color:var(--test_color,#fff);
}
```

```javascript
    const testElement = document.getElementsByClassName('testCssVar')[0];
    let curColor = getComputedStyle(testElement).getPropertyValue("--test_color");
    console.log(curColor); //#c42727

    curColor = 'green';
    //设置过后该DOM元素的字体值变为绿色
    testElement.style.setProperty("--test_color", curColor);
```

- 行内样式中的`CSS变量`获取

```html
<p class="testCssVar" style="--test_color:#c42727;color:var(--test_color,#fff);">西瓜测试行内样式中CSS变量获取</p>
```

```javascript
    const testElement = document.getElementsByClassName('testCssVar')[0];
    let curColor = testElement.style.getPropertyValue("--test_color");;
    console.log(curColor); //#c42727

    curColor = 'green';
    //设置过后该DOM元素的字体值变为绿色
    testElement.style.setProperty("--test_color", curColor);
```

  ---

> 变量覆盖规则

自定义属性同样支持继承。一个元素上没有定义自定义属性，该自定义属性的值会继承其父元素

```html
<div class="one">
  <div class="two">
    <div class="three">
    </div>
    <div class="four">
    </div>
  <div>
</div>
```

```css
.two { --test: 10px; }
.three { --test: 2em; }
```

在这个例子中，`var(--test)`的结果是：

- `class="two"` 对应的节点: `10px`
- `class="three"` 对应的节点: `element: 2em`
- `class="four"` 对应的节点: `10px (inherited from its parent)`
- `class="one"` 对应的节点: 无效值, 即此属性值为未被自定义`css`变量覆盖的默认值

  ---

> 变量自主校验

请注意，如果变量值设置不符合预期规范，则无论是否存在后续默认值，该变量值都会置为最初的默认值，比如设置了非法的颜色值，则会被恢复为`transparent`，同理。

```css
:root{
    --error-color-num:3;
}

.selector {
    color:var(--default-color);
    color:var(--error-color-num,#111);/* transparent */
}
```

  ---

> 注意事项

- 为了和变量名前置的`--`区分，后续变量命名分割都是通过下划线分割。
- 变量名称不能包含`$`，`[`，`^`，`(`，`%`等字符，普通字符局限在只要是`数字[0-9]`，`字母[a-zA-Z]`，`下划线_`和`短横线-`这些组合，但是可以是`中文`，`日文`或者`韩文`。

```css

:root{
    --default-color: #000;
    --error-color-num:3;
}

.selector {
    color:var(--default-color);
    color:var(--error-color-num,#111);/* transparent */ 
    --红色:red;
    background-color: var(--红色);
}
```

**Comment by mowatermelon** [comment]
## 前置知识

### calculate

```css
.road {
    position: absolute;
    width: 100%;
    height: calc(var(--pos_s2) - var(--pos_s1));
    background: var(--road_color);
    top: calc(50% - (var(--pos_s2) - var(--pos_s1))/2);
    transform: translateZ(calc(var(--pillars_height)/7));
    border: var(--skeleton_width) var(--skeleton_color) solid;
    transform-style: preserve-3d;
}

.pillar11 {
    left: 25%;
    top: calc(-1*var(--pillars_height)/2 + var(--pos_s1) - var(--pillars_width)/2);
}
```

---

**Comment by mowatermelon** [comment]
## 前置知识


### translate

```css
.selector {
    transform: translateZ(1px);
}

.selector {
    transform: rotateX(90deg) translateZ(var(--underground_hheight))
}

.selector {
    translateY: (calc(-1*var(--underground_hheight)));
}

.selector {
    transform: rotateX(90deg) translateZ(calc(-60em + var(--underground_hheight))) translateY(calc(-1*var(--underground_hheight)));
}
```

---

### transform-origin

```css
.selector {
    transform-origin: center center 0;
}

.selector {
    transform-origin: 50% 50% 0;
}

.selector {
    transform-origin: 0% 100%;
}

.selector {
    transform-origin: 0% 0% 0px;
}

```

---

### transform-style

```css
.selector {
    transform-style: preserve-3d;
}
```

---

### perspective

```css
.selector {
    perspective:1000px;
}
```

---

**Comment by mowatermelon** [comment]
## 前置知识

### repeating-linear-gradient

```css
.selector {
    background: repeating-linear-gradient(45deg, transparent, transparent 6px, var(--skeleton_color) 6px, var(--skeleton_color) 8px, transparent 8px), repeating-linear-gradient(-45deg, transparent, transparent 6px, var(--skeleton_color) 6px, var(--skeleton_color) 8px, transparent 8px);
}

```

---

### animation-play-state

```css
.selector {
    animation-play-state: paused;
}

.selector {
    animation-play-state: paused, running;
}

.selector {
    animation-play-state: running, running;
}

```

---

### animation-delay

```css
.wave_left_2 {
    animation: wave_left 15s ease-out infinite;
    left: 5%;
    animation-delay: -5s;
}

.wave_left_3 {
    animation: wave_left 15s ease-out infinite;
    left: 5%;
    animation-delay: -10s;
}

.wave_right_1 {
    animation: wave_right 15s ease-out infinite;
    right: 5%;
}

.wave_right_2 {
    animation: wave_right 15s ease-out infinite;
    right: 5%;
    animation-delay: -5s;
}

.wave_right_3 {
    animation: wave_right 15s ease-out infinite;
    right: 5%;
    animation-delay: -10s;
}
```

---

**Comment by mowatermelon** [comment]
## 前置知识

### svg 属性设置

```html
<div class="pillar pillar11">
    <svg class="splash">
        <circle cx="2em" cy="2em" r="3.09879em" stroke-width="2">
            <animate attributeName="r" begin="0s" dur="5s" repeatCount="indefinite" from="0.7em" to="3.5em"></animate>
        </circle>
    </svg>
</div>
```

```css
.pillar>.splash>circle {
    fill: transparent;
    stroke: white;
    animation: splash_anim 10s ease infinite;
    /* Chrome doesn't support animate, Firefox doesn't support this */
}
```

---
