### ISSUE TITLE
2018/12/29

### ISSUE THREAD

**Issue by mowatermelon** [mowatermelon/studyNode#219]
解决 ie 打印时 复选框全选问题

```css
@media print {
  /*注释了tool.css中 @page {    size: a3   }*/
  /*layui.css 去掉 layui-col-xs12 的浮动*/
  html,
  body {
      height: inherit !important; /* 兼容分页问题 */
      -webkit-print-color-adjust: exact; /* 兼容choose打印复选框全选问题 */
  }
  .nowPage {
    height: 100% !important;
    width: 100% !important;
  }
  /* tab页及折叠面板打印分页 */
  .layui-tab-item,
  [outer-container]>.layui-colla-item:not(.ctrlContainer)>.layui-colla-content{
    display: block !important;/* 兼容chorme分页 */
    page-break-after: always;
    clear: both;
  }
```
