### ISSUE TITLE
5.2

### ISSUE THREAD

**Issue by mowatermelon** [mowatermelon/studyNode#28]
```javascript
/*支持语言类型   java ，javascript，c*/
  function happy(){
    console.log("sdsdfa");
  }
```
```python
class Test: //python
   pass
```
```Java
public static void main(String[]args){} //Java
```
```C

int main(int argc, char *argv[]) //C
```
```Bash
echo "hello GitHub"#Bash
```
```cpp
string &operator+(const string& A,const string& B) //cpp
```
***

 |设备	   |分辨率	   |设备像素比率
 | --------   | -----:   | :----: |
  |Android LDPI	|320×240	|0.75
  |Iphone 3 & Android MDPI	|320×480	|1
  |Android HDPI	|480×800	|1.5
  |Iphone 4	|960×640	|2.0

**Comment by mowatermelon** [comment]
原来markdown还可以用来做[ppt](https://talk.linuxtoy.org/using-cli/#1)

**Comment by mowatermelon** [comment]
- animation 属性是一个简写属性，用于设置六个动画属性：
      - animation-name
      - animation-duration
      - animation-timing-function
      - animation-delay
      - animation-iteration-count
      - animation-direction
```css
        .sprite{
          -webkit-animation: spinner 1s infinite ease-in-out;
          animation: spinner 1s infinite ease-in-out;
        }
        @-webkit-keyframes spinner{
          0% {
            -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
          }
          100%{
              -webkit-transform: rotate(40deg);
              transform: rotate(40deg);
            }

        }
```
