### ISSUE TITLE
5.17

### ISSUE THREAD

**Issue by mowatermelon** [mowatermelon/studyNode#36]
技术选型

vue：进行数据绑定以及开发组件

vue-router： 处理页面路由

vuex： 处理各组件间的通讯

vue-resource：处理HTTP请求

element-ui：使用UI框架中部分UI组件进行快速开发

**Comment by mowatermelon** [comment]
```css
ol{list-style-type:none;counter-reset:sectioncounter;width:200px;}  
ol li:before {  
    content:counter(sectioncounter) "、";   
    counter-increment:sectioncounter;  
 }  
```
