### ISSUE TITLE
5.23

### ISSUE THREAD

**Issue by mowatermelon** [mowatermelon/studyNode#39]
今天特别傻  ，想用bootstrap的affix ，先给body赋属性，data-spy :affix,我是想做到左侧的目录导航功能，结果发现各种bug ，这边整理一下，避免以后再犯傻。
> 自定义样式
```css
/* Custom Styles */
    ul.nav-tabs{
        width: 140px;
        margin-top: 20px;
        border-radius: 4px;
        border: 1px solid #ddd;
        box-shadow: 0 1px 4px rgba(0, 0, 0, 0.067);
    }
    ul.nav-tabs li{
        margin: 0;
        border-top: 1px solid #ddd;
    }
    ul.nav-tabs li:first-child{
        border-top: none;
    }
    ul.nav-tabs li a{
        margin: 0;
        padding: 8px 16px;
        border-radius: 0;
    }
    ul.nav-tabs li.active a, ul.nav-tabs li.active a:hover{
        color: #fff;
        background: #0088cc;
        border: 1px solid #0088cc;
    }
    ul.nav-tabs li:first-child a{
        border-radius: 4px 4px 0 0;
    }
    ul.nav-tabs li:last-child a{
        border-radius: 0 0 4px 4px;
    }
    ul.nav-tabs.affix{
        top: 30px; /* Set the top position of pinned element */
    }
```
> 默认的html
```html
<body data-spy="scroll" data-target="#myScrollspy">
<div class="container">
        <div class="col-xs-3" id="myScrollspy">
            <ul class="nav nav-tabs nav-stacked" data-spy="affix" data-offset-top="125">
                <li class="active"><a href="#section-1">第一部分</a></li>
                <li><a href="#section-2">第二部分</a></li>
                <li><a href="#section-3">第三部分</a></li>
            </ul>
        </div>
        <div class="col-xs-9">
            <h2 id="section-1">第一部分</h2>
            <p>partpartpartpartpartpartpartpartpartpart</p>
            <h2 id="section-2">第一部分</h2>
            <p>partpartpartpartpartpartpartpartpartpart</p>
            <h2 id="section-3">第一部分</h2>
            <p>partpartpartpartpartpartpartpartpartpart</p>
        </div>
   </div>
</body>
```
> 默认的js 都是必须要引用的
```javascript
$('#myAffix').affix({
   offset: {
	  top: 100
	  }
})
```
我这边最开始出现的问题是点击左侧的目录树，右侧没有对应跳转，发现是忘记写js，结果在js中引用了之后，页面滚动的时候，右侧的文本会直接浮动到页面最左侧，我以为是我这边bootstrap的js和css版本问题，这边更新了在线地址之后，才发现还是不行，所以我发现了我这边body绑定的data-target目标虽然是对的，但是还是存在问题
```html
<body data-spy="scroll" data-target="#myScrollspy">
```
```html
        <div class="col-xs-3" id="myScrollspy">
```
