### ISSUE TITLE
8.7

### ISSUE THREAD

**Issue by mowatermelon** [mowatermelon/studyNode#69]
```css
    span.icon-bg
    {
        position: relative;
        display: block;
        width: 100%;
        height: 80px;
        margin: 0 auto;
        background-image: url(../../Content/imgs/icon_wmh.png);
        background-repeat: no-repeat;
        background-size: 1170px 100%;
        -moz-border-radius: 10px;
        -webkit-border-radius: 10px;
        border-radius: 10px;
        margin-top: 10px;
    }
    i.icon-bg:before
    {
        position: absolute;
        top: 0;
        left: 0;
        content: '';
        width: 100%;
        height: 100%;
        background-image:url(../../Content/imgs/icon_bg.png);
        background-repeat: no-repeat;
        background-size: 100% auto;
        -moz-border-radius: 10px;
        -webkit-border-radius: 10px;
        border-radius: 10px;        
    } 
    /*登记指南*/
    span.i-djzl
    {
     background-position: 8px 0;   
    } 
    /*收费标准*/
     span.i-sfbz
    {
          background-position: -90px 0;  
    }
    /*办事地点*/ 
    span.i-bsdd
    {
        background-position: -190px 0;        
    }
    /*机构简介*/      
    span.i-jgjj
    {
        background-position: -285px 0;        
    }
    /*不动产定位*/      
     span.i-bdcdw
    {
        background-position: -375px 0;       
    } 
     /*登记申报*/    
     span.i-djsb
    {
          background-position: -475px 0;  
    } 
    /*办理进度*/     
    span.i-bljd
    {
        background-position: -575px 0;        
    }
     /*证书验证*/     
     span.i-zsyz
    {
        background-position: -675px 0;       
    }  
     /*动态新闻*/      
     span.i-dtxw
    {
        background-position: -775px 0;        
    } 
     /*政策文件*/    
     span.i-zcwj
    {
        background-position: -875px 0;       
    } 
    /*登记公告*/     
    span.i-djgg
    {
        background-position: -975px 0;             
    }
     /*法律法规*/     
     span.i-flfg
    {
        background-position: -1075px 0;         
    }
```
