### ISSUE TITLE
8.14

### ISSUE THREAD

**Issue by mowatermelon** [mowatermelon/studyNode#73]
```css
    span.icon-bg
    {
        border: 1px solid;
        position: relative;
        display: block;
        width: 70%;
        height: 60px;
        line-height: 60px;
        text-align: center;
        font-size: 20px;
        margin: 0 auto;
        /* background-image: url(../../Content/imgs/icon_wmh.png); */
        /* background-image: url(../../Content/imgs/icon_bg.png); */
        background-repeat: no-repeat;
        background-size: 100% 100%;
        -moz-border-radius: 10px;
        -webkit-border-radius: 10px;
        border-radius: 100%;
        margin-top: 10%;
    }
```
